import type { ContestRules, Env, Participant, SocialPublication } from './types';
import { ProviderRequestError } from './provider-http';

const defaults = ['pixelfed.social', 'pixelfed.fr'];
const encoder = new TextEncoder();
const decoder = new TextDecoder();

interface ClientRow { host: string; client_id: string; encrypted_client_secret: string }
interface AccountRow { provider_account_id: string; username: string | null; display_name: string | null; encrypted_token: string }
interface PfAccount { id: string; username?: string; acct?: string; display_name?: string; uri?: string; url?: string }
interface PfStatus { id: string; url?: string; uri?: string; content?: string; created_at?: string; visibility?: string; account: PfAccount; media_attachments?: Array<{ url?: string; preview_url?: string }> }

function base64url(bytes: Uint8Array): string { let binary=''; for(const byte of bytes) binary+=String.fromCharCode(byte); return btoa(binary).replaceAll('+','-').replaceAll('/','_').replace(/=+$/u,''); }
function decode64(value: string): Uint8Array { const padded=value.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-value.length%4)%4); return Uint8Array.from(atob(padded),c=>c.charCodeAt(0)); }
async function hmac(value:string, secret:string):Promise<string>{ const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']); return base64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(value)))); }
async function aesKey(secret:string):Promise<CryptoKey>{ return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',encoder.encode(secret)),'AES-GCM',false,['encrypt','decrypt']); }
async function encrypt(value:string,secret:string):Promise<string>{ const iv=crypto.getRandomValues(new Uint8Array(12)); const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(secret),encoder.encode(value))); return `${base64url(iv)}.${base64url(cipher)}`; }
async function decrypt(value:string,secret:string):Promise<string>{ const [iv,cipher]=value.split('.'); if(!iv||!cipher) throw new Error('Connexion Pixelfed invalide. Reconnectez le compte.'); try{return decoder.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode64(iv)},await aesKey(secret),decode64(cipher)));}catch{throw new Error('Connexion Pixelfed illisible. Reconnectez le compte.');} }
function stripHtml(value:string):string{return value.replace(/<br\s*\/?\s*>/giu,'\n').replace(/<[^>]+>/gu,' ').replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&quot;','"').replaceAll('&#39;',"'").replace(/\s*\n\s*/gu,'\n').replace(/[ \t]+/gu,' ').trim();}

export function pixelfedAllowedHosts(env:Env):Set<string>{ const raw=env.PIXELFED_ALLOWED_HOSTS||defaults.join(','); return new Set(raw.split(',').map(v=>v.trim().toLowerCase()).filter(v=>/^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/u.test(v))); }
function assertConfig(env:Env){ if(env.PIXELFED_ENABLED!=='true'||!env.PIXELFED_REDIRECT_URI||!env.DATA_ENCRYPTION_KEY||!env.SESSION_SIGNING_SECRET||!env.DB) throw new Error('Le connecteur Pixelfed n’est pas activé (not enabled).'); return{redirectUri:env.PIXELFED_REDIRECT_URI,encryptionKey:env.DATA_ENCRYPTION_KEY,sessionSecret:env.SESSION_SIGNING_SECRET}; }
function checkedHost(value:string,env:Env):string{ const host=value.trim().toLowerCase(); if(!pixelfedAllowedHosts(env).has(host)) throw new Error(`Choisissez une instance Pixelfed prise en charge : ${[...pixelfedAllowedHosts(env)].join(', ')}.`); return host; }

export function parsePixelfedUrl(input:string,env:Env):{host:string;statusId:string;canonicalUrl:string}|null{ try{const url=new URL(input);const host=url.hostname.toLowerCase();const match=decodeURIComponent(url.pathname).match(/^\/p\/([A-Za-z0-9_.-]{1,64})\/([1-9]\d{5,24})\/?$/u); if(url.protocol!=='https:'||url.port||url.username||url.password||url.search||url.hash||!pixelfedAllowedHosts(env).has(host)||!match)return null; return{host,statusId:match[2],canonicalUrl:`https://${host}/p/${match[1]}/${match[2]}`};}catch{return null;} }
function key(host:string,id:string){return `${host}|${id}`;}
function parseKey(value:string):{host:string;id:string}{const match=value.match(/^([a-z0-9.-]+)\|([1-9]\d{5,24})$/u);if(!match)throw new Error('Publication Pixelfed invalide.');return{host:match[1],id:match[2]};}

async function pfJson<T>(host:string,path:string,init:RequestInit={}):Promise<{data:T;response:Response}>{ let response:Response; try{response=await fetch(`https://${host}${path}`,{...init,redirect:'manual',signal:AbortSignal.timeout(15000),headers:{accept:'application/json',...(init.headers||{})}});}catch{throw new ProviderRequestError('L’instance Pixelfed ne répond pas. Une nouvelle tentative sera effectuée.',true);} const data=await response.json().catch(()=>({})) as {error?:string;message?:string}; if(!response.ok){if(response.status===429||response.status>=500)throw new ProviderRequestError(`Pixelfed est temporairement indisponible (${response.status}).`,true); throw new Error(response.status===401?'La connexion Pixelfed a expiré. Reconnectez le compte.':data.error||data.message||`Pixelfed refuse la requête (${response.status}).`);} return{data:data as T,response}; }

async function getClient(env:Env,host:string):Promise<{clientId:string;clientSecret:string}>{ const config=assertConfig(env); let row=await env.DB!.prepare('SELECT host, client_id, encrypted_client_secret FROM pixelfed_oauth_clients WHERE host=?').bind(host).first<ClientRow>(); if(!row){const created=(await pfJson<{client_id:string;client_secret:string}>(host,'/api/v1/apps',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_name:'TirageSimple',redirect_uris:config.redirectUri,scopes:'read',website:'https://tiragesimple.fr'})})).data;if(!created.client_id||!created.client_secret)throw new Error('Cette instance ne permet pas d’enregistrer l’application TirageSimple.');row={host,client_id:created.client_id,encrypted_client_secret:await encrypt(created.client_secret,config.encryptionKey)};await env.DB!.prepare('INSERT OR REPLACE INTO pixelfed_oauth_clients (host,client_id,encrypted_client_secret,created_at) VALUES (?,?,?,?)').bind(host,row.client_id,row.encrypted_client_secret,new Date().toISOString()).run();}return{clientId:row.client_id,clientSecret:await decrypt(row.encrypted_client_secret,config.encryptionKey)}; }

export async function pixelfedOAuthUrl(env:Env,sessionId:string,instance:string):Promise<string>{const config=assertConfig(env);const host=checkedHost(instance,env);const client=await getClient(env,host);const issued=Math.floor(Date.now()/1000);const nonce=crypto.randomUUID();const encodedHost=base64url(encoder.encode(host));const signature=await hmac(`${sessionId}:${issued}:${nonce}:${host}`,config.sessionSecret);const state=`${issued}.${nonce}.${encodedHost}.${signature}`;const url=new URL(`https://${host}/oauth/authorize`);url.search=new URLSearchParams({client_id:client.clientId,redirect_uri:config.redirectUri,response_type:'code',scope:'read',state}).toString();return url.toString();}

export async function completePixelfedOAuth(env:Env,sessionId:string,state:string,code:string):Promise<void>{const config=assertConfig(env);const [issuedText,nonce,encodedHost,signature]=state.split('.');const issued=Number(issuedText);let host='';try{host=decoder.decode(decode64(encodedHost));}catch{}if(!issued||!nonce||!signature||Math.abs(Date.now()/1000-issued)>600||!pixelfedAllowedHosts(env).has(host)||signature!==await hmac(`${sessionId}:${issued}:${nonce}:${host}`,config.sessionSecret))throw new Error('Connexion Pixelfed expirée ou invalide. Recommencez.');const client=await getClient(env,host);const token=(await pfJson<{access_token:string}>(host,'/oauth/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:client.clientId,client_secret:client.clientSecret,redirect_uri:config.redirectUri,grant_type:'authorization_code',code,scope:'read'})})).data;if(!token.access_token)throw new Error('Pixelfed n’a pas fourni de jeton d’accès.');const account=(await pfJson<PfAccount>(host,'/api/v1/accounts/verify_credentials',{headers:{authorization:`Bearer ${token.access_token}`}})).data;if(!account.id)throw new Error('Compte Pixelfed introuvable.');const providerId=key(host,account.id);const now=new Date().toISOString();await env.DB!.prepare(`DELETE FROM social_accounts WHERE owner_session_id=? AND provider='pixelfed'`).bind(sessionId).run();await env.DB!.prepare(`INSERT INTO social_accounts (id,owner_session_id,provider,provider_account_id,username,display_name,encrypted_token,encrypted_refresh_token,token_expires_at,created_at,deleted_at) VALUES (?,?,'pixelfed',?,?,?,?,NULL,NULL,?,NULL) ON CONFLICT(provider,provider_account_id) DO UPDATE SET owner_session_id=excluded.owner_session_id,username=excluded.username,display_name=excluded.display_name,encrypted_token=excluded.encrypted_token,created_at=excluded.created_at,deleted_at=NULL`).bind(crypto.randomUUID(),sessionId,providerId,account.acct||account.username||null,account.display_name||null,await encrypt(token.access_token,config.encryptionKey),now).run();}

export async function getPixelfedAccount(env:Env,sessionId:string,requiredHost?:string):Promise<{id:string;host:string;username?:string;displayName?:string;accessToken:string}|null>{const config=assertConfig(env);const row=await env.DB!.prepare(`SELECT provider_account_id,username,display_name,encrypted_token FROM social_accounts WHERE owner_session_id=? AND provider='pixelfed' AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1`).bind(sessionId).first<AccountRow>();if(!row||!row.encrypted_token)return null;const [host,id]=row.provider_account_id.split('|');if(!host||!id||requiredHost&&host!==requiredHost)return null;return{id,host,username:row.username??undefined,displayName:row.display_name??undefined,accessToken:await decrypt(row.encrypted_token,config.encryptionKey)};}
export async function disconnectPixelfed(env:Env,sessionId:string):Promise<void>{assertConfig(env);await env.DB!.prepare(`DELETE FROM social_accounts WHERE owner_session_id=? AND provider='pixelfed'`).bind(sessionId).run();}

export async function getPixelfedPublication(input:string,env:Env,sessionId:string):Promise<SocialPublication>{assertConfig(env);const ref=parsePixelfedUrl(input,env);if(!ref)throw new Error(`Utilisez un lien public provenant de ${[...pixelfedAllowedHosts(env)].join(' ou ')}.`);const account=await getPixelfedAccount(env,sessionId,ref.host);if(!account)throw new Error(`Connectez le compte organisateur sur ${ref.host} pour analyser cette publication.`);const status=(await pfJson<PfStatus>(ref.host,`/api/v1/statuses/${encodeURIComponent(ref.statusId)}`,{headers:{authorization:`Bearer ${account.accessToken}`}})).data;if(status.visibility&&status.visibility!=='public'&&status.visibility!=='unlisted')throw new Error('Cette publication Pixelfed n’est pas publique.');if(String(status.account.id)!==account.id)throw new Error('Connectez le compte Pixelfed qui a publié ce post : l’API ne fournit la pagination complète qu’à son auteur.');const authorId=status.account.uri||status.account.url||key(ref.host,status.account.id);return{provider:'pixelfed',providerPublicationId:key(ref.host,status.id),canonicalUrl:status.url||ref.canonicalUrl,authorProviderId:authorId,authorName:status.account.display_name||status.account.acct||status.account.username,title:stripHtml(status.content||'Publication Pixelfed').slice(0,1000),thumbnailUrl:status.media_attachments?.[0]?.preview_url||status.media_attachments?.[0]?.url,publishedAt:status.created_at};}

function nextLink(header:string|null,host:string):string|undefined{if(!header)return;for(const part of header.split(',')){const match=part.match(/<([^>]+)>;\s*rel="?prev"?/iu);if(!match)continue;try{const url=new URL(match[1]);if(url.protocol==='https:'&&url.hostname.toLowerCase()===host&&!url.port&&!url.username&&!url.password&&/^\/api\/v1\/statuses\/[1-9]\d{5,24}\/(?:favourited_by|reblogged_by)$/u.test(url.pathname))return url.searchParams.get('cursor')||undefined;}catch{}}}
export async function getPixelfedParticipantsPage(publicationId:string,pageToken:string|undefined,rules:ContestRules,env:Env,sessionId:string):Promise<{participants:Participant[];nextPageToken?:string;totalResults:number}>{const ref=parseKey(publicationId);checkedHost(ref.host,env);const account=await getPixelfedAccount(env,sessionId,ref.host);if(!account)throw new Error(`La connexion à ${ref.host} n’est plus disponible.`);const interaction=rules.interaction==='reposts'?'reblogged_by':'favourited_by';const endpoint=`/api/v1/statuses/${encodeURIComponent(ref.id)}/${interaction}?limit=80${pageToken?`&cursor=${encodeURIComponent(pageToken)}`:''}`;const {data,response}=await pfJson<PfAccount[]>(ref.host,endpoint,{headers:{authorization:`Bearer ${account.accessToken}`}});const excluded=new Set(rules.excludedUsers.map(v=>v.toLowerCase()));const participants=data.filter(item=>item&&item.id).map(item=>{const providerUserId=item.uri||item.url||key(ref.host,item.id);const username=item.acct||item.username;const blocked=excluded.has(providerUserId.toLowerCase())||Boolean(username&&excluded.has(username.toLowerCase()));return{providerUserId,username,displayName:item.display_name,entriesCount:1,eligible:!blocked,reasons:blocked?['excluded_user']:[]};});return{participants,nextPageToken:nextLink(response.headers.get('link'),ref.host),totalResults:data.length};}
